import string

DELIMITERS = [
  '/',
  ':',
  '·',
  '.',
  '•',
  '×',
  '*'
]

# Amino acid base names and their primary substitution sites
AMINO_ACID_SUB_SITES = {
    'lys': ('lysine', 'Nε'),
    'arg': ('arginine', 'Nω'),
    'his': ('histidine', 'N³'),
    'ser': ('serine', 'O'),
    'thr': ('threonine', 'O'),
    'tyr': ('tyrosine', 'O'),
    'cys': ('cysteine', 'S'),
    'asp': ('aspartic acid', 'β'),
    'glu': ('glutamic acid', 'γ'),
    'asn': ('asparagine', 'Nδ'),
    'gln': ('glutamine', 'Nε'),
    'trp': ('tryptophan', 'N¹'),
    'met': ('methionine', 'S'),
    'orn': ('ornithine', 'Nδ'),
    'hse': ('homoserine', 'O'),
}

# Protecting group definitions
PROTECTING_GROUPS = {'boc': '(tert-butoxycarbonyl)',
 'z': '(benzyloxycarbonyl)',
 'cbz': '(benzyloxycarbonyl)',
 'fmoc': '(9-fluorenylmethoxycarbonyl)',
 'ac': '(acetyl)',
 'alloc': '(allyloxycarbonyl)',
 'dde': '((1-(4,4-dimethyl-2,6-dioxocyclohexylidene)ethyl))',
 'ivdde': '((1-(4,4-dimethyl-2,6-dioxocyclohexylidene)-3-methylbutyl))',
 'mtt': '(4-methyltrityl)',
 'proc': '(propargyloxycarbonyl)',
 'pbf': '(2,2,4,6,7-pentamethyldihydrobenzofuran-5-sulfonyl)',
 'tos': '(tosyl)',
 'mtr': '(4-methoxy-2,3,6-trimethylbenzenesulfonyl)',
 'pmc': '(2,2,5,7,8-pentamethylchroman-6-sulfonyl)',
 'no2': '(nitro)',
 'trt': 'trityl',
 'bn': 'benzyl',
 'bzl': 'benzyl',
 'dnp': '2,4-dinitrophenyl',
 'tbu': 'tert-butyl',
 'acm': 'acetamidomethyl',
 'stbu': 'tert-butyl',
 'mob': '4-methoxybenzyl',
 'mmt': '4-methoxytrityl',
 'npys': '3-nitro-2-pyridinesulfenyl',
 'xan': '(xanthenyl)',
 'for': 'formyl',
 'hoc': '1-(1-adamantyl)-1-methylethoxycarbonyl',
 'o': 'oxide',
 'o2': ',S-dioxide',
 'otbu': 'tert-butyl ester',
 'obut': 'tert-butyl ester',  # typo variant?
 'obn': 'benzyl ester',
 'ome': 'methyl ester',
 'oet': 'ethyl ester',
 'oall': 'allyl ester',
 'ofm': '9-fluorenylmethyl ester'}

# Special cases that don't follow the standard pattern
SPECIAL_CASES = {
 'tyr(2-br-z)': ('tyrosine', 'O-2-bromobenzyloxycarbonyl'),
 'tyr(2,6-cl2-bn)': ('tyrosine', 'O-2,6-dichlorobenzyl'),
 'met(o2)': ('methionine', 'S,S-dioxide'),
}

AA_FULL = {'gly': ['glycine', 'glycyl'],
 'ala': ['alanine', 'alanyl'],
 'val': ['valine', 'valyl'],
 'leu': ['leucine', 'leucyl'],
 'leuc': ['leucine', 'leucyl'],
 'ile': ['isoleucine', 'isoleucyl'],
 'ileu': ['isoleucine', 'isoleucyl'],
 'ser': ['serine', 'seryl'],
 'thr': ['threonine', 'threonyl'],
 'cys': ['cysteine', 'cysteinyl'],
 'met': ['methionine', 'methionyl'],
 'phe': ['phenylalanine', 'phenylalanyl'],
 'tyr': ['tyrosine', 'tyrosyl'],
 'trp': ['tryptophan', 'tryptophyl'],
 'asp': ['aspartic acid', 'aspartyl'],
 'glu': ['glutamic acid', 'glutamyl'],
 'asn': ['asparagine', 'asparaginyl'],
 'gln': ['glutamine', 'glutaminyl'],
 'lys': ['lysine', 'lysyl'],
 'arg': ['arginine', 'arginyl'],
 'his': ['histidine', 'histidyl'],
 'pro': ['proline', 'prolyl'],
 'hyp': ['4-hydroxyproline', '4-hydroxyprolyl'],
 'orn': ['ornithine', 'ornithyl'],
 'dab': ['2,4-diaminobutyric acid', '2,4-diaminobutyryl'],
 'dap': ['2,3-diaminopropionic acid', '2,3-diaminopropionyl'],
 'sar': ['sarcosine', 'sarcosyl'],
 'abu': ['2-aminobutyric acid', '2-aminobutyryl'],
 'aib': ['2-aminoisobutyric acid', '2-aminoisobutyryl'],
 'nva': ['norvaline', 'norvalyl'],
 'nle': ['norleucine', 'norleucyl'],
 'hse': ['homoserine', 'homoserinyl'],
 'hcy': ['homocysteine', 'homocysteinyl'],
 'pen': ['penicillamine', 'penicillaminyl'],
 'sec': ['selenocysteine', 'selenocysteinyl'],
 'pyl': ['pyrrolysine', 'pyrrolysinyl'],
 'aad': ['2-aminoadipic acid', '2-aminoadipyl'],
 'aan': ['α-asparagine', 'α-asparaginyl'],
 'aca': ['2-aminocapric acid', '2-aminocapryl'],
 'agn': ['α-glutamine', 'α-glutaminyl'],
 'ahx': ['6-aminohexanoic acid', '6-aminohexanoyl'],
 'apm': ['2-aminopimelic acid', '2-aminopimelyl'],
 'app': ['γ-amino-β-hydroxybenzenepentanoic acid',
  'γ-amino-β-hydroxybenzenepentanoyl'],
 'asu': ['2-aminosuberic acid', '2-aminosuberyl'],
 'azagly': ['2-azaglycine', '2-azaglycyl'],
 'aze': ['2-carboxyazetidine', '2-carboxyazetidinyl'],
 'bal': ['β-alanine', 'β-alanyl'],
 'bas': ['β-aspartic acid', 'β-aspartyl'],
 'bly': ['3,6-diaminohexanoic acid', '3,6-diaminohexanoyl'],
 'bua': ['butanoic acid', 'butanoyl'],
 'bux': ['4-amino-3-hydroxybutanoic acid', '4-amino-3-hydroxybutanoyl'],
 'cap': ['γ-amino-β-hydroxycyclohexanepentanoic acid',
  'γ-amino-β-hydroxycyclohexanepentanoyl'],
 'cha': ['3-cyclohexylalanine', '3-cyclohexylalanyl'],
 'cit': ['N5-aminocarbonylornithine', 'N5-aminocarbonylornithyl'],
 'cya': ['3-sulfoalanine', '3-sulfoalanyl'],
 'dpm': ['diaminopimelic acid', 'diaminopimelyl'],
 'dpr': ['2,3-diaminopropanoic acid', '2,3-diaminopropanoyl'],
 'dsu': ['2,7-diaminosuberic acid', '2,7-diaminosuberyl'],
 'edc': ['S-ethylthiocysteine', 'S-ethylthiocysteinyl'],
 'ggu': ['γ-glutamic acid', 'γ-glutamyl'],
 'gla': ['γ-carboxyglutamic acid', 'γ-carboxyglutamyl'],
 'glc': ['hydroxyacetic acid', 'hydroxyacetyl'],
 'glp': ['pyroglutamic acid', 'pyroglutamyl'],
 'pglu': ['pyroglutamic acid', 'pyroglutamyl'],
 'har': ['homoarginine', 'homoarginyl'],
 'hhs': ['homohistidine', 'homohistidinyl'],
 'hiv': ['2-hydroxyisovaleric acid', '2-hydroxyisovaleryl'],
 'hva': ['2-hydroxypentanoic acid', '2-hydroxypentanoyl'],
 'hyl': ['5-hydroxylysine', '5-hydroxylysinyl'],
 'igl': ['α-amino-2-indanacetic acid', 'α-amino-2-indanacetyl'],
 'iva': ['isovaline', 'isovalinyl'],
 'lac': ['2-hydroxypropanoic acid', '2-hydroxypropanoyl'],
 'maa': ['mercaptoacetic acid', 'mercaptoacetyl'],
 'mba': ['mercaptobutanoic acid', 'mercaptobutanoyl'],
 'mhp': ['3-hydroxy-4-methylproline', '3-hydroxy-4-methylprolyl'],
 'mpa': ['mercaptopropanoic acid', 'mercaptopropanoyl'],
 'nal': ['3-naphthylalanine', '3-naphthylalanyl'],
 'nphe': ['N-benzylglycine', 'N-benzylglycyl'],
 'nty': ['nortyrosine', 'nortyrosinyl'],
 'oaa': ['ω-amino acid', 'ω-aminoacyl'],
 'oic': ['2-carboxyoctahydroindole', '2-carboxyoctahydroindolyl'],
 '3-pal': ['3-(3-pyridyl)-alanine', '3-(3-pyridyl)-alanyl'],
 'phg': ['2-phenylglycine', '2-phenylglycyl'],
 'pip': ['2-carboxypiperidine', '2-carboxypiperidyl'],
 'pmp': ['β,β-cyclopentamethylene-β-mercaptopropionic acid',
  'β,β-cyclopentamethylene-β-mercaptopropionyl'],
 'pser': ['phospho-L-serine', 'phospho-L-serinyl'],
 'pthr': ['phospho-L-threonine', 'phospho-L-threoninyl'],
 'ptyr': ['phospho-L-tyrosine', 'phospho-L-tyrosinyl'],
 'pya(4)': ['3-(4-pyridinyl)-alanine', '3-(4-pyridinyl)-alanyl'],
 'spg': ['1-amino-1-carboxycyclopentane', '1-amino-1-carboxycyclopentyl'],
 'sta': ['statine', 'statinyl'],
 'thi': ['3-thienylalanine', '3-thienylalanyl'],
 'tac': ['2-tolylaminophenylcabonyl', '2-tolylaminophenylcabonyl'],
 'tic': ['3-carboxyisoquinoline', '3-carboxyisoquinolinyl'],
 'tle': ['3-methylvaline', '3-methylvalyl'],
 'tml': ['ε-N-trimethyllysine', 'ε-N-trimethyllysinyl'],
 'tza': ['3-thiazolylalanine', '3-thiazolylalanyl'],
 'wil': ['α-amino-2,4-dioxopyrimidinepropanoic acid',
  'α-amino-2,4-dioxopyrimidinepropanoyl']}

N_CAPS = {'h2n': '',
 'h': '',
 'nh2': '',
 'cbz': 'benzyloxycarbonyl',
 'z': 'benzyloxycarbonyl',
 'boc': 'tert-butoxycarbonyl',
 'tboc': 'tert-butoxycarbonyl',
 'fmoc': '9-fluorenylmethoxycarbonyl',
 'alloc': 'allyloxycarbonyl',
 'troc': '2,2,2-trichloroethoxycarbonyl',
 'teoc': '2-(trimethylsilyl)ethoxycarbonyl',
 'poc': 'propargyloxycarbonyl',
 'moc': 'methoxycarbonyl',
 'eoc': 'ethoxycarbonyl',
 'azoc': '2-azidobenzyloxycarbonyl',
 'nvoc': '6-nitroveratryloxycarbonyl',
 'ddz': '3,5-dimethoxybenzyloxycarbonyl',
 'ac': 'acetyl',
 'piv': 'pivaloyl',
 'bz': 'benzoyl',
 'tos': 'tosyl',
 'ts': 'tosyl',
 'ms': 'mesyl',
 'mes': 'mesyl',
 'tf': 'trifluoromethanesulfonyl',
 'ns': '4-nitrobenzenesulfonyl',
 'dts': 'dithiasuccinoyl',
 'for': 'formyl',
 'tfa': 'trifluoroacetyl',
 'mtr': '4-methoxy-2,3,6-trimethylbenzenesulfonyl',
 'pmc': '2,2,5,7,8-pentamethylchroman-6-sulfonyl',
 'pbf': '2,2,4,6,7-pentamethyldihydrobenzofuran-5-sulfonyl',
 'bn': 'benzyl',
 'pmb': '4-methoxybenzyl',
 'dmb': '2,4-dimethoxybenzyl',
 'tmb': '2,4,6-trimethoxybenzyl',
 'trt': 'trityl',
 'mmt': '4-methoxytrityl',
 'dmt': "4,4'-dimethoxytrityl",
 'myr': 'Myristoyl'}

C_CAPS = {'h': '', #typo?
 'oh': '',
 'ome': 'methyl ester',
 'och3': 'methyl ester',
 'oet': 'ethyl ester',
 'otbu': 'tert-butyl ester',
 'obn': 'benzyl ester',
 'obzl': 'benzyl ester',
 'oallyl': 'allyl ester',
 'oall': 'allyl ester',
 'oph': 'phenyl ester',
 'otmse': '2-(trimethylsilyl)ethyl ester',
 'otbdms': 'tert-butyldimethylsilyl ester',
 'otips': 'triisopropylsilyl ester',
 'ofm': '9-fluorenylmethyl ester',
 'odmb': '2,4-dimethoxybenzyl ester',
 'opmb': '4-methoxybenzyl ester',
 'onp': '4-nitrophenyl ester',
 'opfp': 'pentafluorophenyl ester',
 'osu': 'N-hydroxysuccinimidyl ester',
 'obt': 'benzotriazol-1-yl ester',
 'oat': '7-azabenzotriazol-1-yl ester',
 'nh2': 'amide',
 'nh': 'amine', #typo?
 'nhme': 'N-methylamide',
 'nme2': 'N,N-dimethylamide',
 'nhet': 'N-ethylamide',
 'net2': 'N,N-diethylamide',
 'nhbn': 'N-benzylamide',
 'nhph': 'N-phenylamide',
 'nhnh2': 'hydrazide',
 'nhnh': 'hydrazide', #typo?
 'conhnh2': 'hydrazide',
 'cho': 'aldehyde',
 'ch2oh': 'alcohol',
 'conh2': 'amide',
 'cf3': 'trifluoromethane'}

COUNTER_ACIDS = {'hcl': 'hydrochloride',
 '2hcl': 'dihydrochloride',
 '3hcl': 'trihydrochloride',
 '4hcl': 'tetrahydrochloride',
 'hydrochloride': 'hydrochloride',
 'hbr': 'hydrobromide',
 '2hbr': 'dihydrobromide',
 'hci': 'hydroiodide',
 'tfa': 'trifluoroacetate',
 'trifluoroacetate': 'trifluoroacetate',
 'acetate': 'acetate',
 'diacetate': 'diacetate',
 'acoh': 'acetate',
 '2acoh': 'diacetate'}

PREFIX_MAP = {
 'me': 'methyl-',
 '(me)': 'methyl-',
 'et': 'ethyl-',
 '(et)': 'ethyl-',
 'ac': 'acetyl-',
 '(ac)': 'acetyl-',
 'for': 'formyl-',
 '(for)': 'formyl-',
 'bz': 'benzoyl-',
 '(bz)': 'benzoyl-',
 'cbz': 'carbobenzyloxy-',
 '(cbz)': 'carbobenzyloxy-',
 'z': 'carbobenzyloxy-',
 '(z)': 'carbobenzyloxy-',
 'boc': 'tert-butoxycarbonyl-',
 '(boc)': 'tert-butoxycarbonyl-',
 'fmoc': 'fluorenylmethoxycarbonyl-',
 '(fmoc)': 'fluorenylmethoxycarbonyl-',
 'ts': 'tosyl-',
 '(ts)': 'tosyl-',
 'ms': 'mesyl-',
 '(ms)': 'mesyl-',
 'tf': 'trifluoroacetyl-',
 '(tf)': 'trifluoroacetyl-'}

GREEK_LETTERS = ['α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ξ', 'ο', 'π', 'ρ', 'σ', 'τ', 'υ', 'φ', 'χ', 'ψ', 'ω']

NON_LATIN1_REPLACEMENTS = {
    # Superscripts
    '⁰': '0',
    '¹': '1',
    '²': '2',
    '³': '3',
    '⁴': '4',
    '⁵': '5',
    '⁶': '6',
    '⁷': '7',
    '⁸': '8',
    '⁹': '9',
    '⁺': '+',
    '⁻': '-',
    '⁽': '(',
    '⁾': ')',

    # Subscripts
    '₀': '0',
    '₁': '1',
    '₂': '2',
    '₃': '3',
    '₄': '4',
    '₅': '5',
    '₆': '6',
    '₇': '7',
    '₈': '8',
    '₉': '9',
    '₊': '+',
    '₋': '-',
    '₍': '(',
    '₎': ')',

    # Greek letters (common ones in chemistry)
    'α': 'a',
    'β': 'b',
    'γ': 'g',
    'δ': 'd',
    'ε': 'e',
    'ζ': 'z',
    'η': 'h',
    'θ': 'th',
    'ι': 'i', 
    'κ': 'k',
    'λ': 'l',
    'μ': 'u', 
    'ν': 'n',
    'ξ': 'x',
    'ο': 'o', 
    'π': 'p', 
    'ρ': 'r', 
    'σ': 's', 
    'τ': 't', 
    'υ': 'y',  
    'φ': 'ph',
    'χ': 'ch',
    'ψ': 'ps',
    'ω': 'o',
    'Α': 'A',
    'Β': 'B',
    'Γ': 'G',
    'Δ': 'D',
    'Ε': 'E',
    'Ζ': 'Z',
    'Η': 'H',
    'Θ': 'Th',
    'Ι': 'I',
    'Κ': 'K',
    'Λ': 'L',
    'Μ': 'M',
    'Ν': 'N',
    'Ξ': 'X',
    'Ο': 'O',
    'Π': 'P',
    'Ρ': 'R',
    'Σ': 'S',
    'Τ': 'T',
    'Υ': 'Y',
    'Φ': 'Ph',
    'Χ': 'Ch',
    'Ψ': 'Ps',
    'Ω': 'O',

    # Other symbols
    '×': 'x',
    '·': '.',  
    '−': '-',  
    '–': '-',  
    '—': '-',  
    '‐': '-',
    '°': '',   
    'Å': 'A',  
    '’': "'",
    '′': "'",  
    '″': '"',   
    '®': '', 
    '™': '', 
    '•': '.', 
    '±': '+-',
    '→': '',
    'ü': 'u',
    'ø': 'o',
    'ö': 'o'
}

COMMON_CHARS_WHITELIST = list(
    string.ascii_letters + string.digits + string.punctuation + " "
)
